name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Test-Mappings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.5.0
          registry-url: https://registry.npmjs.org/
      - name: install yarn and test
        run: |
          yarn 
          yarn build
          yarn test
        working-directory: ./bulla-contracts
